### ISSUE TITLE
[task] Gradle build script

### ISSUE THREAD

**Issue by MikeNeilson** [opendcs/opendcs#105]
- [x] opendcs.jar
- [x] docs (sphinx/rtd)
- [x] installer

**Comment by MikeNeilson** [comment]
This is working in the 8.0 branch. There are currently no plans to backport to 7.0

**Comment by adamkorynta** [comment]
As per workshop presentation. Goal is to back port gradle to 7.0.14

**Comment by adamkorynta** [comment]
Closing due to duplicate in: https://github.com/opendcs/opendcs/issues/689
