### ISSUE TITLE
[task] create a container or containers for various OpenDCS programs

### ISSUE THREAD

**Issue by MikeNeilson** [opendcs/opendcs#108]
Given that more and more adminstrative or even terminal access to servers is going away from most users and many want to be "cloud native" it would be good to setup some sort of containerization.

Possible methods thereof:

- Run as a WAR (doesn't have to be a web services, things like Tomcat/Jetty are "Application Servers", but it can include HTTP endpoints for just health and some minor interaction)
- Docker containers

NOTE: these are not mutually exclusive, if we do the first one that 2nd has a fairly clear path. But there would be issues with listening on arbitrary ports/protocols... but no insurmountable.

**Comment by agilmore2** [comment]
Would be nice to have an LRGS container for sure. I could see a decoding
container pulling webdata isolated from other systems, although OpenDCS is
currently quite the monolith of a jar.

I've been playing quite a bit with containers in the last few months,
they're fascinating.

Andrew

**Comment by mikecovesw** [comment]
Almost all LRGS administrative functions can be done using DDS throught the real-time status (rtstat) GUI. Some things that cannot be done include:
- stop/start the server
- viewing the quality.log stats
- browsing/searching the full "lrgslog" info
- resetting administrative passwords if you have lost them

**Comment by MikeNeilson** [comment]
Good to know, the start/stop is handled by the container engine itself. but the logging will be an issue to consider.

A first go will likely have LRGSHOME on what's called a "volume" in docker, (think separate file system.) Longer term using databases may be better... even if just sqlite on a volume so the code is all consistent.

But that'll all shake out as development begins.
