### ISSUE TITLE
CWMS Connection Pool mechanism leaking connections during RouteScheduler

### ISSUE THREAD

**Issue by MikeNeilson** [opendcs/opendcs#117]
**Describe the bug**
Eventually the system exits because no connections are available.

**To Reproduce**
1. setup system (making sure tracing is turned on)
2. run routsched
3. watch logs
4. see after freeConnection see number increase

**Expected behavior**
connections close system is stable.

**Desktop/ServerSide (please complete the following information):**
 - OS: Ubuntu 22.04/Java 11
 - Version: master branch latest

Continuing to investigate.

**Comment by MikeNeilson** [comment]
it's crazy but it's happening within like 20 minutes or less. So crazy, but at least I don't have to wait much.

**Comment by mikecovesw** [comment]
When I was first implementing the JOOQ stuff, I had debugs showing the # of connections for each get/free call. Also at one point I had it printing a stack trace so I could find the offending code that wasn't closing.

**Comment by MikeNeilson** [comment]
And that came in really handy. I traced it to the LoadingApplicationDAO.
The prepared statements were calling getConnection().preparedStatement(...) instead of the getting the connection and closing it later. This particular run of routingSpec had on the fly transformations enabled.

I started just migrating the calls to the new Lambda handlers. Figured if I'm going to tweak it might as well update to the new mechanism. Got pretty far before end of my normal work day. Will dig back in tomorrow morning.

**Comment by MikeNeilson** [comment]
FYI, traced it to here: https://github.com/opendcs/opendcs/blob/b2f8a8f0c936e59f88bf7e8d47b7d9bc039dc2c7/src/main/java/opendcs/dao/LoadingAppDao.java#L641

After a call to this function set there were several connections left open. Likely due to the use of getConnection().preparedStatement() not having a matching freeConnection call.
