### ISSUE TITLE
DECODES format statement bug:  setMissing(ND)

### ISSUE THREAD

**Issue by jbatterman** [opendcs/opendcs#121]
I'm trying to use the OpenDCS web pull features to process USGS data using USGS Water Services.  For seasonal sites, the USGS uses the symbol "Ssn" to denote missing data.  I'm trying to decode that data as missing, not an error.  In the latest manual, I found the following notes:

![image](https://user-images.githubusercontent.com/116035268/196276673-bca1dc2a-33f3-4522-b57c-272f24a302f7.png)

I set up my format statement using setMissing(Ssn), but it does not read the value as missing.  If I manually change my RDB file to show "///" instead of "Ssn", a known symbol for missing values, the value is parsed correctly.  See screenshot below, specifically the "data" format statement for processing the values.  I tested putting the setMissing code in each of the format statements as well with the same result.

![image](https://user-images.githubusercontent.com/116035268/196277080-e2a2d293-9d70-4345-be2c-6fbeaeab3cb0.png)

**Comment by adamkorynta** [comment]
Looks like the "P"\s in the last column is what is throwing things off. 

If I removed, then it successfully flags as missing:

![image](https://user-images.githubusercontent.com/47677856/199333943-f2610162-4b4c-4e62-9dff-392dc1b05286.png)

I'll look into why the "\tP" characters are getting picked up.
