### ISSUE TITLE
Computation failed retry cleanup has SQL syntax problem

### ISSUE THREAD

**Issue by agilmore2** [opendcs/opendcs#123]
**Describe the bug**
https://github.com/opendcs/opendcs/blob/master/src/main/java/decodes/tsdb/TimeSeriesDb.java#L1009
Replacement markers in prepared statements cannot be inside single quotes.

Results in
```
WARNING 10/19/22 15:24:43 hdb removing items from task list failed:
WARNING 10/19/22 15:24:43 hdb java.sql.SQLException: Invalid column index
	at oracle.jdbc.driver.OraclePreparedStatement.setIntInternal(OraclePreparedStatement.java:5223)
	at oracle.jdbc.driver.OraclePreparedStatement.setInt(OraclePreparedStatement.java:5210)
	at oracle.jdbc.driver.OraclePreparedStatementWrapper.setInt(OraclePreparedStatementWrapper.java:209)
	at decodes.tsdb.TimeSeriesDb.releaseNewData(TimeSeriesDb.java:1212)
	at decodes.tsdb.ComputationApp.runApp(ComputationApp.java:479)
	at decodes.tsdb.TsdbAppTemplate.execute(TsdbAppTemplate.java:249)
	at decodes.tsdb.ComputationApp.main(ComputationApp.java:673) 

```

**To Reproduce**
1. Enable retries
2. Fail a computation
3. SQLException leads to CP exit

**Expected behavior**
No exception, retry cleanup handled correctly.

**Desktop/ServerSide (please complete the following information):**
 - RHEL 7 
 - 6.8-rc14, bug also exists in 7.0.1

**Additional context**
Seems like a logic issue where old failed record cleanup only occurs when other computations fail?

**Comment by MikeNeilson** [comment]
`					+ "INTERVAL '? hour')" ); //String.format(maxCompRetryTimeFrmt, maxRetries) + ")"); //`

the '? hour' should be `? || ' hour'`

**Comment by MikeNeilson** [comment]
maybe with a to_char/format statement... can't remember that part off the top of my head.

**Comment by MikeNeilson** [comment]
well, or ::text in postgres

**Comment by agilmore2** [comment]
There's an example of ? usage in the same statement a few lines up, I believe the right answer is "INTERVAL ? hour)" but I don't know the interval syntax well.

**Comment by agilmore2** [comment]
I'd nominate this bug for fixing before 7.0.2, as computation retries do not work at all currently for any SQL database.

**Comment by MikeNeilson** [comment]
Is that a new thing or something that's been going on for a while? I ask because while I don't disagree, the connection pool thing for CWMS makes the entirety of OpenDCS real-time processing very problematic. No one is using computation retries (granted that's probably because it's never actually worked.) 

But for me, the stability of what was just fixed would free up the mental space to work on it.

**Comment by agilmore2** [comment]
I expect they've been broken for a while.

This appears to be a place where the database implementations differ. Postgres intervals may allow literal replacements in INTERVAL '?' hour, but Oracle does not. Further, Oracle datemath when subtracting sysdate - date_time_loaded results in number of days+fractional days.

**Comment by agilmore2** [comment]
I'd like to see that patch merged for 7.0.2, let me know.

**Comment by MikeNeilson** [comment]
Yeah, that shouldn't be an issue.

**Comment by MikeNeilson** [comment]
actually, technically this would just be a situation of doesn't "release" 7.0.2 and we jump to .0.3. Artifacts with the name 7.0.2 are already in the wild.

**Comment by agilmore2** [comment]
Thanks. I would suggest tagging 7.0.2-pre or some such, I guess.

Glad to see the connection pooling issues overcome!
