### ISSUE TITLE
catch in PythonAlgorithm is too broad

### ISSUE THREAD

**Issue by Gaelmare** [opendcs/opendcs#149]
https://github.com/opendcs/opendcs/blob/792c8ab4a9c42be14e34a430340942e9cb3f475b/src/main/java/decodes/tsdb/algo/PythonAlgorithm.java#L311

This catches even the SystemExit Exception raised when sys.exit(0) is called in the python code, which makes quiet short-circuit exits of the code impossible. 

I propose a more specific catch of SystemExit checking for a zero error code that's silent thereafter.

**Comment by MikeNeilson** [comment]
That seams reasonable to me.
