### ISSUE TITLE
Logging -> JUL, keep what we have but allow more control?

### ISSUE THREAD

**Issue by MikeNeilson** [opendcs/opendcs#161]
Would anyone think I'm totally insane if I just went and did one big pull request to convert the logging to java.util.logging?

Assuming the following:

- I can find a clean way to handle the GUI elements (like the compedit/run/trace dialog
- Additional configuration *will not* be required. E.g. puting -dN and -l will behave as normal, just mapping as appropriate to the JUL bits.

I just went looking through the code to see about creating a logging system that can keep a number of files and, well, it's there already. But the echo system is not setup to let the user really user it. 

I'm thinking default mappings from the usual parameters, but if logging.properties exists in say, LRGSHOME or DCSTOOL_USERDIR, pick it up and use it. (Mapping the name of course. That may mean stealing the Tomcat JUL implementation instead of just using the default.)

We can discuss other frameworks later. However my inclination is no, as while currently all of OpenDCS is pure application, it would be good to leave the modules, like DECODES scripts and the like, open for consumption in other systems. 

Alternatively I could just keep going with #100, but honestly why maintain our own logging system if we don't have to?

NOTE: I have no idea when I would do this, but I don't suspect it would be difficult, just a smidge time consuming and drudgeworky.

**Comment by MikeNeilson** [comment]
note that's not to say the existing implementation was wrong to exist or bad; the project has been around a while and JUL, et all, didn't exist.
It wouldn't be difficult to expand upon, but then we are maintain another full system that has its own challenges versus just doing the OpenDCS specific data processing work.

**Comment by adamkorynta** [comment]
Something to consider along the lines of Tomcat logger, if there is a common logger used across dependencies, that might make a good candidate so that we don't have multiple logging configs. Not to say that dependencies should dictate the application logger, but it could help alleviate choice fatigue.

**Comment by cappelaere** [comment]
LOG4J2??

**Comment by MikeNeilson** [comment]
that's a good point Adam, but I know for a fact there isn't. the HEC code uses flogger. something uses SLF4j (keeps putting a message in the nohup files.)


Log4j2 probably would still leave a bad taste in peoples mouth. I mean, they fixed it, so that's not a hard no. I've just mostly only used JUL directly and haven't really had the sometimes over simplicity annoy me enough to really look at something else.

Now, one thing that would sell a different logger. does the configuration allow some basic substitution at runtime for say the file name of the log. My gut reaction is the simplest thing is native JUL, but a light config wrapper to handle that say `comproc` might be called with `comproc -a <custom name` and need it's own log file.

Though to be fair, all of those loggers (slf4j,log4jN, logback, etc) will hijack the JUL calls, so if I just up and changed it to JUL to be on a standard logging system, it would not be difficult to justify a different logger latter or allow a downstream implementer to override. Where a special feature was needed could be changed, while a lot of the code remains native JUL.

**Comment by agilmore2** [comment]
+1 to JUL!

**Comment by MikeNeilson** [comment]
I did a quick review of the JUL code. It does let us alter the configuration at runtime. So we can keep some default behavior (like setting the file on the command line.)

Additionally we can create arbitrarily named loggers and add handlers on a whim for them. For example for the trace function in in the config editor.

So I'm probably going to take a stab at this in the next month or so. Not a terrible distraction if other efforts are making me bang my head against the wall.

**Comment by adamkorynta** [comment]
Take a look at the HEC class `MarkingClassLogger` to see how they are resolving the "arbitrarily named loggers" for cross-cutting concerns. It handles both the enclosing class as well as a marking class so that you either enable logging for entire features or turn it on for a specific class, which is really nice. In order to do the same thing with JUL you'd need to define conventions instead.

**Comment by MikeNeilson** [comment]
Thanks I'll keep that in mind.

**Comment by MikeNeilson** [comment]
Okay, I've reviewed a few different articles and such, and the slf4j manual. I'm going to go with slf4j to start this effort.
Since one of our goals is to allow these jars to work in different areas, like say embedded in a servlet container, it makes sense to use something that provides a nice interface but abstracts out the actual logging framework. Which is what SLF4j does.

So by default we'll be using JUL to actually do the log file write, I'm going to shift everything to the SLF4j fascade.

Now, I just have to figure how to do that all relatively cleanly.

**Comment by MikeNeilson** [comment]
I'm going to close this, we've started the migration of at least the front end logging to slf4j. We'll open a new ticket/discussion when the time to change the backend comes.
