### ISSUE TITLE
Install: giving a relative path for install directory fails to install paths correctly

### ISSUE THREAD

**Issue by agilmore2** [opendcs/opendcs#166]
During console install, giving a relative directory will write the decj script with a relative path. This causes all tools to fail unless executed from a specific directory.

The first setting in decj looks like this when bug occurs:
```
# INSTALL_PATH will be replaced with actual DECODES install dir.
DH=7.0.4
```

**To Reproduce**
1. java -jar <installer>.jar -console
2. Type 1, <relativepath>,1,1,1,1,1,1,1,1,1
3. cat relativepath/bin/decj
4. observe that decj DH setting is a relative path

**Comment by MikeNeilson** [comment]
Overcome by events, I think, INSTALL_PATH is only used by the installer to write the files out, the scripts no detect where they exist and use that location for operations.

**Comment by MikeNeilson** [comment]
Additionally overcome by the decision to use a simple zip distribution.
