### ISSUE TITLE
Allow filtering in OpenDCS DECODES Lists

### ISSUE THREAD

**Issue by jbatterman** [opendcs/opendcs#187]
**Is your feature request related to a problem? Please describe.**
It can be very difficult to have to scroll through a very large list to find a specific Platform, Site, or Config (as we continue to expand our web pulls other tabs may become large and unwieldy, too).

**Describe the solution you'd like**
In certain GUIs in OpenDCS, you can filter to a location to narrow down the list that is shown.  It would be nice to have a filter at the top of each tab in DECODES, where you can type a location (doesn't have to be as sophisticated as CWMSVue) or something, and have the list filter down to only show lines that have that location in them.

**Comment by MikeNeilson** [comment]
Totally agree. 

However, I wouldn't expect the team as is to get to this quickly as we're still dealing with database stability issues. However, if you want it faster Scott may be able to work on it, or you fund someone directly.

**Comment by jbatterman** [comment]
Thanks!  I'll send this his way and see if he can get it on the to-do list.  @hoffmanjs

**Comment by agilmore2** [comment]
@BrettPWRE may be interested in working on it if we get Reclamation to approve. Let us know if Scott's not picking it up.

**Comment by MikeNeilson** [comment]
Scott is going to give it to old college try. However, given how some of those screens are designed it's likely there will be a lot of just cleanup he does and plenty of work to go around.
