### ISSUE TITLE
Produce signed installation jar

### ISSUE THREAD

**Issue by Gaelmare** [opendcs/opendcs#193]
Saw the release artifacts for 7.0.5 and didn't see a signature .asc for the installer. Would be good to have.

**Comment by MikeNeilson** [comment]
Yeah, I noticed that too, still working on some other parts will generate a signature today or tomorrow.

**Comment by MikeNeilson** [comment]
just uploaded. will and that signature to the release task with a few staging-for-next fixes I'm also working.
