### ISSUE TITLE
Updating laptop installations fails

### ISSUE THREAD

**Issue by agilmore2** [opendcs/opendcs#196]
Have several users reporting that updating an OpenDCS instance is not longer working in 7. This used to work in 6.8rc15.
I suspect paths aren't updated or properties or overwritten or some such.

**Desktop/ServerSide (please complete the following information):**
Seen on several desktops and server installations. I usually install in a clean location myself, but many others do not.

**Comment by MikeNeilson** [comment]
We no logger have an installer or support in place upgrades of the software.
