### ISSUE TITLE
Platforms Tab - Platform Column Names

### ISSUE THREAD

**Issue by jbatterman** [opendcs/opendcs#200]
**Describe the bug**
When using dcstool_start.bat, then clicking DECODES Database Editor, the initial GUI popup draws the Platforms table as expected.  If DECODES is closed, another editor is opened/closed, then DECODES is reopened from the toolbox, the Platforms table "Platform" column has different names.

**To Reproduce**
1. Open dcstool_start.bat
2. Open DECODES Database Editor
3. Close DECODES Database Editor
4. Open Time Series Groups Editor
5. Close Time Series Groups Editor
6. Open DECODES Database Editor

**Expected behavior**
The table should look the same as the initial GUI open.

**Screenshots**
![InitialOpen](https://user-images.githubusercontent.com/116035268/225118529-3e19f5a7-1995-4098-9bb8-1b9d38c26a1d.png)
![SecondOpen](https://user-images.githubusercontent.com/116035268/225118538-cd3ffd25-4bad-4e1c-a60c-cc9400e72193.png)

**Desktop/ServerSide (please complete the following information):**
 - OS: Windows 10
 - Version:  7.0.1

**Additional context**
I believe the initial Platform column is created using a column from the Sites tab + the Designator, if there is one.  The initial open seems to use the "cwms" column from the Sites tab in most cases.  The second open seems to use a different column, or perhaps a different association all together.

**Comment by MikeNeilson** [comment]
After having reviewed some of the code for unrelated reasons I suspect your assessment in in Additional Context is correct.

The "Model" that holds the data and lets the GUI system actually render it is likely not getting reset correctly between runs. Additionally it is likely the same actual instance of the GUI which just makes it more likely that things aren't getting reset correctly.

**Comment by MikeNeilson** [comment]
Have you tried this again since setting the siteNameTypePreference. I wasn't able to recreate the issue just now.

**Comment by jbatterman** [comment]
I should have hopped on here once we tested - no, we haven't run into this issue again since setting the siteNameTypePreference.  Thank you!
