### ISSUE TITLE
schema setup scripts do not create "utility" loading application entry so compimport step fails 

### ISSUE THREAD

**Issue by agilmore2** [opendcs/opendcs#215]
While creating an new TSDB instance, the compimport step almost at the end of createDB.sh failed because the "utility" loading application id is not present yet.

I created it manually to continue.

**Comment by MikeNeilson** [comment]
that's pretty much an all databases issue. I was planning to start dealing with it when I implemented an integration test for at least one of the timeseries SQL databases.

**Comment by agilmore2** [comment]
It's more an ordering thing, the utility app is created in the next import.

**Comment by MikeNeilson** [comment]
That import will fail because there's now defined utility app. It's a bootstrap issue, the "utility" app needs to be inserted within the SQL scripts during database creation.

**Comment by agilmore2** [comment]
dbimport appears to work fine without it, and dbimport is creating the
loading app entries, so should be just a matter of reordering the imports.

**Comment by MikeNeilson** [comment]
So while setting up my homelab I did the loading app import first and everything worked correctly.
