### ISSUE TITLE
Simple HTTP health endpoint

### ISSUE THREAD

**Issue by MikeNeilson** [opendcs/opendcs#235]
**Is your feature request related to a problem? Please describe.**
Cloud services generally want a simple system to check the health of containers.

**Describe the solution you'd like**
A simple HTTP services embedded with not generally customary "/health" and extra information.
It is also practical to add "/metrics" at the same time and at least expose limited JVM metrics while we begin adding others.

**Describe alternatives you've considered**
The docker file could have a health/status script embedded that various container engines can just use. However, we have other efforts that will benefit from having an HTTP service in place so I think just starting that is a good solution. The effort will be small so we should be able to easily revert if it proves problematic.

**Additional context**
I'm requesting infrastructure for some internal work and realized I need a way to access the status of each running instance and existing tools, such as complocklist and the event monitor aren't practical in the AWS ECR/ECS environment.

**Comment by agilmore2** [comment]
So is this the first foot in the door for an actual API? ;)

This sounds great.

**Comment by MikeNeilson** [comment]
That's the idea. We'll see how it integrates, if at all, with other knownish efforts going on. But I feel we shouldn't wait on code, or even a basic description of intended design and library selection, not submitted when we have a need.

**Comment by MikeNeilson** [comment]
The same caveat on timing as #220 will apply. my $work has a direct need now, but I don't mind switching it later if it makes sense. Especially considering that since it's HTTP the backend should never have to matter to the user.
