### ISSUE TITLE
Platform List Panel not usable on fresh install

### ISSUE THREAD

**Issue by MikeNeilson** [opendcs/opendcs#278]
**Describe the bug**
A new database with no platforms is causing none of the interface of that tab to render. It is just impossible to even add one.

**To Reproduce**
1. Setup a fresh Install
2. Open dbedit
3. See the lack of controls on the platform tab

**Expected behavior**
The list should just be empty and the controls rendered like the other tabs.

**Screenshots**
![image](https://github.com/opendcs/opendcs/assets/7980296/c6608a53-4d26-46e7-8cb3-e644088dbb43)

**Desktop/ServerSide (please complete the following information):**
 - OS: Windows
 - Version 7.0.8
 - References "OpenTSDB" database.

**Additional context**

**Comment by tcitjack** [comment]
I am running into this same issue.  Any update on a fix??

**Comment by MikeNeilson** [comment]
It's fixed for the next release, we're just also having other issues with
that release. It'll be within the next 2 weeks though.

**Comment by tcitjack** [comment]
Awesome thanks!  Would you be able to send an example of a platformlist.xml file?  I think we can construct one if we had an example to go off of.

**Comment by MikeNeilson** [comment]
Yeah, I'll try to create a small example. However, if you are able to run the build and do 
`ant integration-test -Dno.docs=true -Dopendcs.test.engine=OpenDCS-XML` a valid edit-db will be created that you can copy in.

**Comment by MikeNeilson** [comment]
apologies, I was going to create an example and kept getting side-tracked. were you able to get started at all?

**Comment by tcitjack** [comment]
No apology necessary!  Yes we downloaded a copy of the 709 unreleased version and were able to generate our platform list xml.  Now were just working on getting the route scheduler working.  Appreciate the follow up!

**Comment by MikeNeilson** [comment]
Excellent. thanks!
