### ISSUE TITLE
Computation using ScalerAdder Algorithm does not recognize existing time series

### ISSUE THREAD

**Issue by jbatterman** [opendcs/opendcs#279]
**Describe the bug**
This behavior occurs whether editing an existing computation, creating a new computation, or copying an existing computation.  For computations using the ScalerAdder algorithm, selecting an input time series fails most of the time.  Error states no such time series.

**To Reproduce**
1. Open Computation Editor
2. Open NWO-MTNE-Flow computation (or copy it, or create a new comp)
3. In the Time Series Parameters section, click one of the input rows and click Edit.  Either type in the Location part or use the Select button to find the desired location.  Use the Time Series Lookup button to select from available time series.
4. When clicking OK at the bottom, most of the time an error is thrown that states "No such time series.  Input parameters for non-group computations must refer to time series that already exist."
5. Some time series do work - it seems to be random to me, I cannot find a connection between all the time series that break and the ones that work.  Example NWDM time series that work:  MTMC.Stage.Inst.1Hour.0.Best-NWDM, BIS.Stage.Inst.15Minutes.0.Raw-LRGS, BIS.Flow.Inst.1Hour.0.Best-NWDM.  Example NWDM time series that do not work:  OMA.Stage-Orifice.Inst.15Minutes.0.Raw-LRGS, OMA.Flow.Inst.1Hour.0.Best-NWDM, DENE.Flow.Inst.1Hour.0.Best-NWDM, LEGDV.Flow.Inst.1Hour.0.Raw-CODWR-Web.

**Expected behavior**
Expect any time series available in the Time Series Lookup button (or in the CWMS database) to be available to save without error.

**Screenshots**
Error:
![image](https://github.com/opendcs/opendcs/assets/116035268/6d46f1d0-72a8-45ec-8b85-a536a6fd1456)

**Desktop/ServerSide (please complete the following information):**
 - OS: Windows 10
 - Version:  Occurs in Windows Version 6-8-RC14 and Version 7-0-RC01.  Server side is 6.8 as well.

**Additional context**
NWDM does have enabled computations that utilize ScalerAdder successfully.  I'm unsure which GUI version was utilized when creating the computations, but potentially they were created before we began using the Windows client and this issue did not occur on the server.

**Comment by MikeNeilson** [comment]
I'll try that on the HEC T7 as well. That's really odd.

**Comment by jbatterman** [comment]
@MikeNeilson any update on this?  NWO needs to be able to create these time series in order to move forward with their MMC Lower South Platte model.  We just tried again after you fixed our sequencing issues and are seeing the same error.

One note on this, all the time series were created with an abstract web pull through OpenDCS.  It's our CO DWR web pull, which is stored directly to the database with the Routing Scheduler.  We did notice that all these time series do not have a time zone defined in their metadata - is there something we need to add to the web pull properties to add that, and could that be what's causing the issue somehow?  Katie is pulling from our Version "Raw-CODWR-Web" time series.

**Comment by jbatterman** [comment]
I posted this too soon.  Katie tested adding the time zone using the CWMS Locations tab and re-adding it, but still got the same error.  Tested with LEGDV.

**Comment by jbatterman** [comment]
This issue is still present even with the time zone changes to the shell and opendcs properties in NWDM.  I see the same error when testing time series.

**Comment by hoffmanjs** [comment]
Looking through the code the siteNameTypePreference is used in determining which siteName is selected.  The siteNameTypePreference can be set in the decodes.properties file.  Setting siteNameTypePreference=CWMS seems to fix the issue.

**Comment by ktarbet** [comment]
@jbatterman ,  @hoffmanjs     may we close this issue?   Is that setting siteNameTypePreference=CWMS working ?

**Comment by hoffmanjs** [comment]
Should be able to close this issue.  Was working when I tested it.
