### ISSUE TITLE
OpenDCS 7.0.8 Gui Fix does not show all decoding scripts

### ISSUE THREAD

**Issue by JasonDSS** [opendcs/opendcs#297]
**Describe the bug**
OpenDCS 7.0.8 Gui Fix does not show all decoding scripts when an older version 6.8.14 does.

**To Reproduce**
1. Copy edit-db folder from 6.8.14 and replace the one in 7.0.8
2. Launch the GUI interface for 7.0.8 and click on DECODES Database Editor
3. Go to configs tab and click on any config with multiple decoding scripts
4. 7.0.8 does not show all decoding scripts, but they're in the xml file. Attached example where the older version sees ST and RD decoding scripts, but 7.0.8 sees only RD

**Expected behavior**
Should show all decoding scripts

**Screenshots**
OpenDCS 7.0.8 not showing the ST Decoding script:
![image](https://github.com/opendcs/opendcs/assets/143829980/cf485345-55fd-4dd9-929f-6a3ef04c92b2)

ST Decoding script picked up by an older OpenDCS, version 6.8.14:
![image](https://github.com/opendcs/opendcs/assets/143829980/9f851e72-54c4-46c0-afd9-4e7e65559ef5)

**Desktop/ServerSide (please complete the following information):**
 - OS: Windows
 - Version 10
[DA-Omnisat-019.txt](https://github.com/opendcs/opendcs/files/12500310/DA-Omnisat-019.txt)

**Additional context**

**Comment by JasonDSS** [comment]
Tried several versions, and it appears version 7.0.5 is the last one that doesn't have this issue.

**Comment by MikeNeilson** [comment]
That tracks. I think i roghly kniw what the issue it.

Fyi it may have been my phone download, but the export is cutoff at the end
and doesnt have the other script.

**Comment by MikeNeilson** [comment]
oh quick question just to make sure I don't run down the wrong path. what this with getting reading from oracle with 7.0.8 or an XML based database?

**Comment by JasonDSS** [comment]
This is 7.0.8 trying to read an XML database

**Comment by hoffmanjs** [comment]
I compared version 6.8.14 and 7.0.8.  Both versions worked exactly the same.  Both versions reading from an oracle database.

**Comment by MikeNeilson** [comment]
That make sense. The way the XML data is read is different and I probably missed an edge case when I was fixing it from the first time I made a tweak.

**Comment by ktarbet** [comment]
I've created a test that I believe reproduces the issue.  However, I need advice how to use a simple XML test database.  
Should I create a resource and unzip the test-database into a temporary directory as part of the test ?

https://github.com/ktarbet/opendcs/blob/explore-issue-297/src/test/java/decodes/xml/XmlDatabaseTest.java

**Comment by ktarbet** [comment]
Additional Note: If I save the config, by clicking commit, the Decodes Script (that is not showing, but in the xml) gets lost.

**Comment by MikeNeilson** [comment]
> Additional Note: If I save the config, by clicking commit, the Decodes Script (that is not showing, but in the xml) gets lost.

That makes sense to me. I think it always rewrites everything.

**Comment by MikeNeilson** [comment]
> I've created a test that I believe reproduces the issue. However, I need advice how to use a simple XML test database. Should I create a resource and unzip the test-database into a temporary directory as part of the test ?
> 
> https://github.com/ktarbet/opendcs/blob/explore-issue-297/src/test/java/decodes/xml/XmlDatabaseTest.java

I wouldn't zip it up, but have the test "xml database" for that test be in a sub-folder fully expanded. The build tool will pass in the system property "build.dir" and the resource will be in `<build.dir>/test-resources/`

**Comment by ktarbet** [comment]
@MikeNeilson , or anyone,   Please suggest some direction, I'm not familiar with the XML parsing code here.

I'm in the debugger, using the test case in the Draft PR,  I watched the following code run twice (for script1, and script2), so both scripts are pushed in the hier (XmlHierarchyParser).  However, only script2 survives the full xml reading.

This is in PlatfomConfigParser.startElement(...)

```java
scriptBuilder = DecodesScript.from(scriptParser).platformConfig(platformConfig).scriptName(nm);

hier.pushObjectParser(scriptParser);

**Comment by ktarbet** [comment]
Could this , apparently related, commit have clues:

https://github.com/opendcs/opendcs/commit/a1c83feea28e0b1c55c178c6c1831cc639dafdeb

**Comment by MikeNeilson** [comment]
Yeah. should that implies that the 2nd script should get loaded and makes me wonder if it's even running this section for the 2nd script.
