### ISSUE TITLE
Add option to dbexport to strip all password fields

### ISSUE THREAD

**Issue by MikeNeilson** [opendcs/opendcs#330]
**Is your feature request related to a problem? Please describe.**
dbexport currently writes passwords in clear text. This is fine...ish for an actual backup but it terrible if we need someone to upload their config for additional testing.

**Describe the solution you'd like**
Simple command line switch to strip any username/password fields, mostly datasource arguments.

**Describe alternatives you've considered**

**Additional context**

**Comment by ktarbet** [comment]
@dvdho @zamusacelre  and I are considering default to not show passwords, and create an argument -include-password if you want passwords exported in the XML dump.

**Comment by MikeNeilson** [comment]
That seems reasonable to me. The should be an explicit option.

**Comment by ktarbet** [comment]
ah... not done yet... There can be passwords under  <LoadingApplication ...   

<AppProperty name="password">insert password here</AppProperty>
