### ISSUE TITLE
Ability to Scrape HTML pages and parse data through OpenDCS

### ISSUE THREAD

**Issue by jbatterman** [opendcs/opendcs#338]
**Is your feature request related to a problem? Please describe.**
The abstract web pull in OpenDCS allows you to read web pages and parse data for multiple gages if the web page is consistent and readable (i.e., CSV).  It may be able to read HTML and parse but there's not enough documentation/examples out there for me to figure that out.  We have one web page that we have to scrape and look for keywords to parse data, and to my knowledge there's not a way to do that through OpenDCS.  If there is please let me know!

**Describe the solution you'd like**
A way to scrape an HTML page and look for data, storing it into CWMS time series.

**Describe alternatives you've considered**
We currently do this with a java program written by @hoffmanjs that runs on the cron on our T7 server.  Our understanding from what we've been told about the cloud migration is that these jobs cannot be there in CWBI, and we need to look at alternative ways to get the data.

**Additional context**
The program visits the URL (https://cnppid.com/wp-content/uploads/2016/06/lakeRiverData.html) and scrapes Lake McConaughy data, Keystone diversion data, and North Platte RIver at North Platte data.  This website is the only automated way to ingest this data - the other data on the site we are pulling from its source (NE DNR).

**Comment by MikeNeilson** [comment]
Actually scraping HTML data is a bit more complex that what the DECODES language would allow. Too many possible variations.

However, it *should* be made easier to make custom decodes functions similar to algorithms. This would be the preferred approach:

- Create an SPI (Java Service Provider Interface) for decodes functions
- migrate the existing functions to this system
- Implement reasonable new functions (for example USGS data or CDA)

However as fair warning this will require a lot of automated testing and is part of why I did the initial tweak to the code to allow testing DECODES scripts outside an install. But even with tests we managed to break the XML database so anyone who does this should proceed, just with caution -- and an expectation that test have to be made with the code but not that everything has to work perfectly; the group will help with that.

**Comment by ktarbet** [comment]
@jbatterman @hoffmanjs 

@MikeNeilson mentioned custom decodes functions above.    I think shefprocess() method is an example, that is called in DECODES scripts for parsing Shef data.  That pattern could be useful for something like custom HMTL parsing.  Here is the ShefProcess Example:  https://github.com/opendcs/opendcs/blob/master/src/main/java/decodes/decoder/ShefProcess.java

**Comment by ktarbet** [comment]
The SHEF decoding is nearly working in the test.  However, the last value (of the SHEF time-series) is missing when using the Junit/DecodesHelper.  When using the UI the last value is OK.

**Comment by ktarbet** [comment]
@hoffmanjs  and I explored a SimpleRegexParser that could take care of this specific case.   Below is a 'paper' design.

![image](https://github.com/opendcs/opendcs/assets/4818531/380aec25-9db7-4e32-8a1b-f623b75d275a)

A regular expression will be entered in the properties under name = regex,   and the first capture group will be returned.
A property regexRemoveComma can be used for pages that have values such as 2,345.6  (the comma will be removed before converting to a double)

![image](https://github.com/opendcs/opendcs/assets/4818531/2ccce2f7-84dc-49a7-94d5-35b40ee8493f)

![image](https://github.com/opendcs/opendcs/assets/4818531/912dea4e-54fd-4bf1-867a-4f17af0d3d4b)

**Comment by MikeNeilson** [comment]
Decodes functions can take parameters. Would it make sense to provide the regex as an input instead of a property?
That would allow multiple uses which could be very useful.

**Comment by ktarbet** [comment]
We were thinking the simpleregexparser would iterate over each sensor and run a separate regex for each sensor.
We could have a bigger regex that get all sensors, with multiple capture groups?  or multiple regex arguments to the method.

**Comment by ktarbet** [comment]
The regex property could override, optional Decodes argument .

**Comment by MikeNeilson** [comment]
That all sounds rather difficult. Trying to use a regex for HTML asking for trouble but if you keep the problem a bit more constrained it's probably manageable.

Even what you propose probably wouldn't work generically. if you pass the regex as a parameter to process the current available text, you each this flexibility.

The java regex system supports named capture groups. you can find examples in the cwms_database flyway migration branch but it's fairly straight forward. So it wouldn't be too difficult to automatically map a capture group to a sensor.

I'm also not convinced the sensor should know how to parse it's data. The Config Sensors are used in multiple scripts, this could be multiple scripts using a regex, how would it know which one to do?  And having the platform need to know breaks the separation of concerns even further.

The shefparsers and NOS* decodes functions take over completely because it's really the only thing they can do. But in either case they really shouldn't be "DECODES" language functions but an entirely different parser.

This regex parser idea fits better with the general idea of the existing "normal" (for lack of better term) decodes functions where they are configured within the script and not external.

**Comment by ktarbet** [comment]
Thanks for that explanation and Ideas.    Visually this what I translated,  for using named captures and a new decodes function:

![image](https://github.com/opendcs/opendcs/assets/4818531/3d12a29d-84b5-4c3b-8f93-75906df6f663)

**Comment by MikeNeilson** [comment]
Yeah that makes sense as a rough out. (s1 would need a >s2 at the end to actually move to the next statement, but that's separate from the overall design)

Just Regex would probably be appropriate. Not sure what a "not SimpleRegex" would be here.

**Comment by ktarbet** [comment]
Here is the latest; no longer 'paper' but real code now.
![image](https://github.com/opendcs/opendcs/assets/4818531/5f2bb975-2523-4a69-9648-c594086409c2)

**Comment by agilmore2** [comment]
This could be a neat step towards heuristic data loading, something I've
thought about often when writing data loaders. Not something I'd want to do
in production, but when a user is attempting to create a new data source,
would be a fun thing to have a system try a bunch of different decoding
configurations to see if something works well. If I was writing a
commercial package, I'd be looking at this type of thing as a
distinguishing feature.

I'm not completely sold on the capture group naming prefix "sensor", as
I've seen some wacky ids from groups like the State of Colorado.

Andrew

**Comment by ktarbet** [comment]
The updated version uses sensor number ; this avoids any odd named sensors., and consumes characters so you could use
two identical regex's to work through a file as shown below.

![im-34-regex-decodes-function](https://github.com/opendcs/opendcs/assets/4818531/59c32d81-edd1-4215-8bfd-19b6ed527783)

**Comment by agilmore2** [comment]
Looks pretty good to me!
