### ISSUE TITLE
CCP Renames Timeseries Output to Location Alias Instead of CWMS Location

### ISSUE THREAD

**Issue by msweier** [opendcs/opendcs#375]
**Describe the bug**
Sometimes a computation in CCP will force a location alias CCP instead of the CWMS  location name. The timeseries with the location alias is not always found when using the desktop version, but can using the server version.

**To Reproduce**
1. With OpenDCS 6.8 RC14 PC version, go to 0-LockDam_02-GateOpeningTG computation in the MVP database.
2. You may get an error when it opens saying it cannot find the timeseries for the "OpenRiver" parameter saying the timeseries doesn't exist or you may get an error when trying to run it. Replace the location of the timeseries name with LockDam_02, and it will replace it with HSTM5 (the NWS alias), but it should run. If it does not, try launching it from the server and it will run. I've seen this happen with ScalarAdder20 algorithms too.

**Expected behavior**
When the output is named the CWMS location, it should remember the CWMS location.

**Screenshots**
![image](https://github.com/opendcs/opendcs/assets/9432394/98c1aeec-6eed-4d07-8250-22110147b7fc)

**Desktop/ServerSide (please complete the following information):**
 - OS: Windows
 - Version 6.8 RC 14

**Comment by MikeNeilson** [comment]
Well, the good news is, while confusing, the computation WILL, reference the correct time series.

Unfortunately I'm not quite sure how we would appropriate make that interface alias aware. OpenDCS doesn't save the timeseries name, it saves the ts_code number. If you selected an alias it would revert to the "real" location name. If you selected the real time and got an alias though that's definitely a bug.

That said, we could probably make the system alias aware using the properties below, but it would be a bit of manual work to allow selecting which alias type you want to see.

**Comment by msweier** [comment]
I guess it doesn't bother me when it computes; however, sometimes it will not compute using the desktop version and I have to open it on the server. However, when I open it on the server I get this error:
![image](https://github.com/opendcs/opendcs/assets/9432394/8533abfa-21f1-4259-a72b-2a2bf3ffd39d)

And the location is blank. I can set it to the CWMS loc, but it doesn't seem to stick. It's been computing automatically via a CCP process though. 
![image](https://github.com/opendcs/opendcs/assets/9432394/7a8c36a3-7612-42fc-a5a8-7ed8fc9bbdec)

I think it may be related to this behavior where I see different locations depending on if I view it via the server or desktop application. 
![image](https://github.com/opendcs/opendcs/assets/9432394/e458d21d-ea6b-441c-bd23-6444ae9a6d56)

**Comment by MikeNeilson** [comment]
Huh, that is rather odd. Wonder if that's related to #279
