### ISSUE TITLE
Improve DCS Connectivity to Database

### ISSUE THREAD

**Issue by msweier** [opendcs/opendcs#378]
**Is your feature request related to a problem? Please describe.**
After about 10 min, DCS will lose connection on the desktop version. The server application also has this issue, but it lasts longer. I've found this is not long enough when working on an algorithm or computation with a lot of inputs.

**Describe the solution you'd like**
 It would be nice to have a setting where you can have dcs ping the database at a set interval to maintain connection.

**Describe alternatives you've considered**
I've found if I have the Routing Monitor or Process Monitor open in the background the connection stays open longer.

**Comment by MikeNeilson** [comment]
This is a known issues and is getting worked on. The changes to properly support this are what led to the 7.0 series and we're still dealing with the changes that are required.

I am a bit surprised it's only 10 minutes though, but I'm going to close this as it's already one of our large goals covered by multiple issues.

See https://github.com/orgs/opendcs/projects/14 for current progress and known issues.
