### ISSUE TITLE
OpenDCS Toolkit Profiles

### ISSUE THREAD

**Issue by jbatterman** [opendcs/opendcs#405]
**Describe the bug**
When you open the toolkit (using dcstool_start.bat or launcher_start.bat), if you have profiles enabled there is a dropdown on top to choose which profile to log in with.  NWDM has this enabled to make COOPing easier - the user can select a profile rather than editing their decodes.properties file every time.  We have two profiles, NWO and NWK.  There is also the "default" profile.  In older versions of OpenDCS, utilizing the profiles worked as expected.  In the newest version of the GUI, our added profiles do not work.  The toolkit allows you to select them, but clicking on a component takes you to the login screen and then disappears without ever popping up a new GUI of that component.  Keeping the Profile as "default" will work to open the additional components.

**To Reproduce**
1. Go to dcstool_start.bat or launcher_start.bat, double-click to open toolkit
2. On the Profile dropdown, select NWO-T7 (rather than the default of "default")
![image](https://github.com/opendcs/opendcs/assets/116035268/a993c677-1ffd-443c-a09d-7402aae83296)
4. Click on DECODES Database Editor, or another component
![image](https://github.com/opendcs/opendcs/assets/116035268/4a202262-acfc-4729-9a56-92635b6cf064)
5. Enter username/password.  The loading screen and login screens disappear, and no additional GUI ever opens.

**Expected behavior**
The additional component GUI should open after login.

**Desktop/ServerSide (please complete the following information):**
 - OS: Windows 10
 - Version OPENDCS 7.0.10

**Additional Context**
When using the "default" profile, log information is populated in the command window that opens with the batch file.  When using the user-defined profile, no log information is populated.

**Comment by MikeNeilson** [comment]
Okay, so two problems:
1. the default isn't handle correctly, the system always looks in $DCSTOOL_HOME/decodes.properties
2. This whole system just isn't working at all on windows.


1 is easy to fix and has something staged. 2 is going to take a minute and likely involve some rework.
