### ISSUE TITLE
Decoding issues using the GUI Interface

### ISSUE THREAD

**Issue by NathanHolcomb** [opendcs/opendcs#413]
While completing initial testing on 7.0.11 I found issues decoding data via the GUI interface using platforms and decoding configurations that worked properly on 7.0.8. After talking with our IT team they are also completing similar testing and have not experienced the issue when using scripts to run the decoding config. As a result, the problem appears to only occur when using the GUI interface

1. Setup a know Platform with a decoding configuration that has worked using the GUI interface on previous versions
2. Use the GUI interface to bring up the DCP Message Browser
3. Run the message browser to show both Raw and Decoded values for the Platform
Example of 7.0.11 not decoding properly (doesn't appear to find the Platform in general)
![image](https://github.com/opendcs/opendcs/assets/104468193/ff492828-dfd2-4842-92b5-5bd49afad080)

**Expected behavior**
Example of 7.0.8 properly decoding with the same Platform and Decoding Config:
![image](https://github.com/opendcs/opendcs/assets/104468193/57e0523b-5aa4-4eb3-b3a7-e020d8bbac57)

**Desktop/ServerSide:**
![image](https://github.com/opendcs/opendcs/assets/104468193/2cf3faf1-fbd5-4f8a-b545-08a4e5481b21)

Platform and decoding configuration (in TXT format) that were used for testing both 7.0.8 and 7.0.11:

[p00130.txt](https://github.com/opendcs/opendcs/files/13676049/p00130.txt)

[Nos6Min.txt](https://github.com/opendcs/opendcs/files/13676052/Nos6Min.txt)

**Comment by MikeNeilson** [comment]
is this using the XML database?

**Comment by NathanHolcomb** [comment]
Yes, had to transfer files to TXT for the ticket but they came from the XML database.

**Comment by MikeNeilson** [comment]
And I was just able to recreate this in CWMS.

**Comment by NathanHolcomb** [comment]
Awesome, thank you for the quick fix Mike!

**Comment by MikeNeilson** [comment]
No problem.
FYI please don't close issues with open pull requests. They'll automatically close when the changes are actually merged in.

**Comment by NathanHolcomb** [comment]
Ahh got it, thanks again!
