### ISSUE TITLE
Committing a config file also commits all platforms associated with that config

### ISSUE THREAD

**Issue by jbatterman** [opendcs/opendcs#429]
**Describe the bug**
When committing an open config file, all the platforms connected to that config are also committed, even if no platforms are open in DECODES and in spite of not being on that tab.

**To Reproduce**
1. Go to the NWDM DECODES Database
2. Activate the Configs tab, and then click on and open a config that is connected to a platform that does not have a Site associated with it.  When we found this but, it was with the web-CODWR-Flow config file.  Those platforms have been deleted from the database now, but the NWK-CLIM-001 config would allow you to reproduce this error now with only one platform instead of multiple platforms.
3. Hit Commit on the open config file.  An error GUI will pop up stating "Cannot save platform without site assignment".  In NWDM's case, this Error pop-up occurred multiple times (there were multiple platforms without sites connected to this config).  In the example case that you can use in testing, there is only one platform connected to this GUI without a site and the error only pops up once before allowing you to move around in the editor again.
4. See error screenshot below.
![image](https://github.com/opendcs/opendcs/assets/116035268/169bf2e5-1a3a-4016-ab39-1704730e40a7)

**Expected behavior**
The expected behavior of a "Commit" on a specific file is that it would only commit that open file.  Not any other files on that tab or on any other tabs.  File --> Commit All is what we would expect would commit all files (or all open files).

**Screenshots**
Open NWK-CLIM-001 config file.
![image](https://github.com/opendcs/opendcs/assets/116035268/26827466-1304-4159-9e38-8a03dc8a6283)

Hit Commit, see error:
![image](https://github.com/opendcs/opendcs/assets/116035268/648ac9d0-7c69-4cb9-b098-98fdfb72593d)

See related platform that is causing the error:
![image](https://github.com/opendcs/opendcs/assets/116035268/4cd42cdd-ec4c-4c41-a2a8-569b774ffd4b)

**Desktop/ServerSide (please complete the following information):**
 - OS: Windows 10, OpenDCS 7.0.1
 - Version 6.8.14

**Additional context**

**Comment by MikeNeilson** [comment]
Unfortunately that's a fundamental part of the implementation which stems from the XML database.
I think I have a sense of how to fix it, but I need to write things up more and share with others.

It's unfortunately going to take a while - At least for everything.

We can probably fix the "configs" relatively quickly. But it'll still be a few weeks of work I think.

**Comment by MikeNeilson** [comment]
Okay, the good news is I might be wrong about how complex the fix is. It's definitely because of the XML database design but I think I've discovered a simple workaround. Going to try and test it a bit more thoroughly though. Not a drastic change, just makes me paranoid given the other issues we've had.
