### ISSUE TITLE
Python Alogorithm Scripts - Column sorting issue

### ISSUE THREAD

**Issue by ktarbet** [opendcs/opendcs#449]
**Describe the bug**
Sorting confuses the 'Select CP Functions Function' dialog
**To Reproduce**
using windows Client (building from master 7.0.12), connected to a CWMS Database

1. open Computations
2. Open a python algorithm
3. Click 'CCP Built-in' button
4. Click Name column to sort.
5.Click the 'screening' under Name.

Before Sorting Description is correct as shown for screening for example:
![image](https://github.com/opendcs/opendcs/assets/4818531/7ab4faf7-2915-410c-89af-1367b92c1c5f)

After Sorting
![image](https://github.com/opendcs/opendcs/assets/4818531/5f38aa3f-fbce-4d72-a307-4d730b253356)

**Comment by msweier** [comment]
This is present in both the server and client GUI when trying to "Copy" a comp, algo etc... in the other tables too. If just selecting, the correct row is selected, but trying to "copy" triggers the bug.

**Comment by ktarbet** [comment]
> This is present in 7.0.11 both the server and client GUI when trying to "Copy" a comp, algo etc... in the other tables too. If just selecting, the correct row is selected, but trying to "copy" triggers the bug.

Looks like the copy issue is addressed in https://github.com/opendcs/opendcs/pull/462/files
