### ISSUE TITLE
OpenDCS does not install for all users as Windows Admin

### ISSUE THREAD

**Issue by krowvin** [opendcs/opendcs#47]
**Describe the bug**
When running the opendcs install (double click icon) on Windows OpenDCS is not installed (shortcut) to all users desktop. 

The checkbox to install for all users is grayed out. 

**To Reproduce**
1. Download OpenDCS Jar
2. Double click icon to run
3. Attempt to install for all users

**Expected behavior**
Icon/install should be available for all users in Windows

**Desktop/ServerSide (please complete the following information):**
 - OS: Windows 10
 - Version: 6.8.14

**Additional context**
Tim with BOR ECAO Loveland, CO asked this question during the OpenDCS presentation.

**Comment by DanielTOsborne** [comment]
It might be because the Java installation tool can't handle UAC elevation.

As a workaround, you could try opening a Command prompt as Admin, then change to the directory where you have the JAR file, and execute
`java -jar opendcs.version.jar`

**Comment by MikeNeilson** [comment]
We no longer use an installer
