### ISSUE TITLE
Login Dialog password is slowing down users workflow

### ISSUE THREAD

**Issue by ktarbet** [opendcs/opendcs#514]
With the new showable password, Typing:  username{tab}password appends to default password, from the resources.

**Describe the solution you'd like**

The Password text box should be blank, unless it is remembering my password for me.

**Additional context**

![image](https://github.com/opendcs/opendcs/assets/4818531/ba160f1b-144d-4389-a74f-0206eed04ef6)

**Comment by MikeNeilson** [comment]
Nah, i screwed that up and somehow didn't notice. it should start blank and not save it.
