### ISSUE TITLE
PlatformListIO should use bind variables

### ISSUE THREAD

**Issue by ktarbet** [opendcs/opendcs#523]
**Component to be refactored**

PlatformListiO.java needs refactoring for bind variables, primary for performance reasons.

**Proposed method**

Follow other examples in the code that has moved to bind variables.   SiteDAO for example, simplifies binding  work by using a method doQuery(...) , inherited from DaoBase.   

**Additional context**

PlatformListIO extends SqlDbObjIo, so I'll study this code. However, I welcome advice on how to approach my first bind-variable refactor in OpenDCS.

**Comment by MikeNeilson** [comment]
Unfortunately, I generally don't recommend starting with the `SqlDbObjIo` based elements. The overall design is rather... off in regards to the rest of the system.

That said I don't think it would be terribly difficult. You'll likely need to follow the existing scheme but the `DaoHelper` class can take and `java.sql.Connection` and the `DatabaseConnectionOwner` and gives you access to the new handlers.

Go slow. Don't overthink it. The good news with PlatformListIO, that's used in the existing integration tests, so you may not need to create additional tests.

**Comment by ktarbet** [comment]
I've started slow in the commit above.   I'm not sure why I had to modify the generic public interface ThrowingConsumer
to explicitly include DatabaseException.

```java
@FunctionalInterface
public interface ThrowingConsumer<T,E extends Exception>
{
    public void accept(T value) throws E, DatabaseException;
}
```

**Comment by MikeNeilson** [comment]
> I've started slow in the commit above. I'm not sure why I had to modify the generic public interface ThrowingConsumer to explicitly include DatabaseException.
> 
> ```java
> @FunctionalInterface
> public interface ThrowingConsumer<T,E extends Exception>
> {
>     public void accept(T value) throws E, DatabaseException;
> }
> ```

That's an issue with Java, you can't pass a vargs list for the generics.
The solution is to remove DatabaseException from where, and catch anything that isn't `SQLException` in the handler and rethrow, preferably with a bit extra detail, as a `SQLException`.

If you look at the sections I've previously updated you'll see that done.

It's not the prettiest thing in the world but just adding DatabaseException here isn't correct, that particular class is intended for generic operations, not just the database.
