### ISSUE TITLE
Display Default Properties Options under "Sources" Tab when new Source is created. And drop down menu of Name options and Value options for Names.

### ISSUE THREAD

**Issue by zamusacelre** [opendcs/opendcs#545]
**Feature**
Include default list of Names under Properties when a new source is added.

![image](https://github.com/opendcs/opendcs/assets/104451600/286e750f-37da-4bc0-a768-6290b25a83c5)

**Current behavior**
Currently when a new source or type is added, the Properties section is empty and it is up to the user to enter and type the name of the property.  One suggestion is also when the Add Button is clicked that a drop down menu of current Name options show up.  And within that option when a particular Name is selected, it would be nice is a default drop down of the options shows up.

**Comment by ktarbet** [comment]
@zamusacelre ,  How about a button 'Add Defaults' that will add all properties with default values (that are not already added)?

When we get to step 4 - in the blue annotated steps,  we would know that the WebDataSource (web) is selected, so the properties could be added at that point.

**Comment by MikeNeilson** [comment]
It shouldn't require user intervention. The other interfaces all do this automatically. I'm pretty sure even some of the DataSources already do. I suspect the information is not being passed through getSupportedProperties correctly.

**Comment by ktarbet** [comment]
I'll follow the pattern in RoutingSpecEditPanel.java, where the properties update automatically when you change the various combo boxes.
