### ISSUE TITLE
Unable to import hidden algorithms using compimport (trying to import Stat.xml)

### ISSUE THREAD

**Issue by zamusacelre** [opendcs/opendcs#547]
**Describe the bug**
When I try to import Stat.xml I am getting Permissions Denied.

**To Reproduce**
1. Using version 7.0.4 
2. On server, become DCSA user
3. Try running commands in documentation to import stats algorithms 
![image](https://github.com/opendcs/opendcs/assets/104451600/f81ce4fc-ac74-404a-ba16-31c0e24e76a9)

4. Then getting following error:  
![image](https://github.com/opendcs/opendcs/assets/104451600/273080cb-3a9b-4bbb-a5b9-f871cc31227e)

5. Goal is to be able to use hidden algorithms

**Expected behavior**
A new algorithm shows up in the Algorithm tab once the command is run (presumable without error/warnings)

**Desktop/ServerSide (please complete the following information):**
 - USACE server

**Comment by MikeNeilson** [comment]
It's trying to make a log in the current directory. which is doesn't have permission to write to. We should probably update the docs to have the users do that in the `$DCSTOOL_USERDIR` directory and use the full path, or with shell variables, to the input XML.

Probably wouldn't hurt to create a better error message too. Pretty sure we can get enough info from java to do so.

**Comment by zamusacelre** [comment]
I just tried your suggestion and now I'm getting this: 
![image](https://github.com/opendcs/opendcs/assets/104451600/d0a68e4b-a1d2-42e9-9b5a-5dac7b75db24)

**Comment by zamusacelre** [comment]
Here is a conceptual question (of which I am not going to delete anything). If someone deletes a "default" algorithm from the algorithm tab in the Computation Editor - does this mean any of the following: 
1) We have deleted the algorithm from the database.  True/False
2) It will let us delete it if it is being used in a computation.  True/False
3) If the algorithm was indeed one of the default algorithms it is retrievable. True/False
4) It is retrievable because the xml or jar files are in the installation and can be reimported? (permissions & location of commands pending). True/False

Thanks!

**Comment by MikeNeilson** [comment]
1.  False, just the reference used to find the actual Java "class"
2.  False, there is a database level constraint to prevent that.
3. Truish, I think there's a few that haven't had the xml generated
4. True, assuming there is an XML file available (or the users knows what to manually put in within the compedit -> algorithms tab -> new
5. False, within the database they are different entries. the execClass is not part of the uniqueness (otherwise you wouldn't be able to put it in.)

**Comment by MikeNeilson** [comment]
> I just tried your suggestion and now I'm getting this: ![image](https://private-user-images.githubusercontent.com/104451600/318982879-d0a68e4b-a1d2-42e9-9b5a-5dac7b75db24.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIwOTkxODksIm5iZiI6MTcxMjA5ODg4OSwicGF0aCI6Ii8xMDQ0NTE2MDAvMzE4OTgyODc5LWQwYTY4ZTRiLWExZDItNDJlOS05YjVhLTVkYWM3Yjc1ZGIyNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwMlQyMzAxMjlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01NzM0YmRlNGVkMTNkYmQ2ZWU4N2RkOTdmOTgwMWMxMzI3Yjc3M2U0ZWZkN2QxZTdmYzI3Y2IxNDZlNzdkNTg2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.a0EUfMu_dt2sETC7nb_13su7kxPbEUCdD-JYFf4eb9M)

Odd, there may be incorrect permissions on that file. I will try to check tomorrow.
