### ISSUE TITLE
Algorithm - Exec-Class Empty Drop-down Options 7.0.12

### ISSUE THREAD

**Issue by zamusacelre** [opendcs/opendcs#558]
**Describe the bug**
Using OpenDCS 7.0.12 PC Client - after install (using release from GitHub), the Algorithm Exec-Class Options are Empty.  

**To Reproduce**
1. Install 7.0.12 PC Client (with CWMS Components upon install)
2. Open Computation Editor - Navigate to Algorithms Tab
3. Under the List of Algorithms - Create  New One (or edit an existing one)
4. Notice that the Exec Classes are missing.

**Expected behavior**
It is expected to see a drop down menu of the Exec Classes and options.  

**Screenshots**
![image](https://github.com/opendcs/opendcs/assets/104451600/136984d5-1cc1-4844-ae19-59a2a8b64fd2)

**Desktop/ServerSide (please complete the following information):**
 - Windows PC

**Comment by MikeNeilson** [comment]
Hmm, I might close this, I need to look at some of the other tickets, but that particular box isn't possible to fill in... well, or it might be. Need to think about it.

**Comment by zamusacelre** [comment]
OK, this was noted/brought up by at least two Districts (Jacksonville) & LRE.  I am pretty sure it used to have the drop down in the older versions.  My thoughts are that if the drop down exists, people will be more likely to use the algorithm .  As it stands, even with the improvements and additions to the documentation, it puts a lot of responsibility on the end-users to search for and enter the proper exe class and name of the algorithm.  Most users are not as savy or going ot have the time to search through and find this information.

**Comment by MikeNeilson** [comment]
I don't think that particular field ever had a drop down. It's possible there was something similar in the rledit program as it uses a similar mechanic.

The challenge is that just having that class isn't enough in the algorithms tab to setup an algorithm, you also need to know all the inputs and properties. There's not a good way to do that at the moment. But it is in the works (though mostly thought process at this point.)

**Comment by zamusacelre** [comment]
Oh I see your point.  Right I could be thinking of something else, or just thinking of how the boxes are populated for algos whose names are there.  Now just thinking outloud - I do sort of think having these bein the rledit or somethign like that could be helpful, so that users don't have to have everything present, but can select/hide what is showing up.

**Comment by ktarbet** [comment]
in the code:  

"opendcs\src\main\java\decodes\tsdb\compedit\AlgorithmsEditPanel.java"   There is existing code that looks for algorithms.txt
It appears the file is missing so a simple dialog is presented instead of a nice list to choose from.

```java
// If couldn't load the algorithms.txt lists, then revert to JOptionPane.
		if (execSelectDialog == null)
		{
			String cn = JOptionPane.showInputDialog(null, "Enter full Java class name with package prefixes:");
			if (cn == null)
				return;
			execClassField.setText(cn);
			return;
		}
```

**Comment by ktarbet** [comment]
@dvdhoz  is looking into this issue.

**Comment by MikeNeilson** [comment]
That seems a brittle way to deal with things. All of the algorithms have to ultimately derive from `DbAlgorithmExecutive`
You can scan the classpath at runtime (though definitely cache the result) to build a list.

**Comment by agilmore2** [comment]
If this information is not filled in for existing algorithms, that's an
oddity, as the Java class path is part of the algorithm properties.

**Comment by MikeNeilson** [comment]
This is for when you are manually adding a new algorithm, so by definition the system wouldn't know anything about it.

(Granted existing algorithms *should* have already been imported in, but when setting up from scratch it's not actually obvious how to go about that.)

**Comment by ktarbet** [comment]
Here is more about 'algorithms.txt' from the documentation.  

https://github.com/opendcs/opendcs/blob/master/docs/source/legacy-cp-userguide.rst

And I found this below in an older version - It belongs under doc\ , which I didn't realized I removed in a previous PR.

```
decodes.cwms.rating.CwmsRatingMultIndep CWMS Rating with multiple independent input parameters
decodes.cwms.rating.CwmsRatingSingleIndep CWMS Rating with a single independent input parameter
decodes.cwms.validation.CwmsScreeningAlgorithm Validation from CWMS-resident screening records
decodes.cwms.validation.DatchkScreeningAlgorithm Validation from DSS DATCHK files
decodes.tsdb.algo.AddToPrevious Adds current value to previous value in the database
decodes.tsdb.algo.AverageAlgorithm Outputs a periodic average of a single input parameter
decodes.tsdb.algo.BridgeClearance Given property low-chord, output clearance from input waterLevel parameter.
decodes.tsdb.algo.ChooseOne Given two input params, if one is outside set limits, output the good one.
decodes.tsdb.algo.CopyAlgorithm Copy input to output, with optional multiplier and offset
decodes.tsdb.algo.CopyNoOverwrite Copy input to output, but don't overwrite existing values in the database.
decodes.tsdb.algo.DisAggregate Spread input values over shorter interval output by fill, interpolate, or split.
decodes.tsdb.algo.EstimatedInflow Output estimated inflow = delta(storage) + average outflow over period.
decodes.tsdb.algo.FillForward Project an input value by copying it forward in time for specified # intervals.
decodes.tsdb.algo.HdbACAPSRating Implements ACAPS rating algorithm for HDB
decodes.tsdb.algo.HdbEvaporation Given area and evaporation coefficient, estimates evaporation
decodes.tsdb.algo.HdbRating HDB Rating using HDB-resident Rating Tables
decodes.tsdb.algo.HdbReservoirMassBalance HDB Mass Balance Equation
decodes.tsdb.algo.IncrementalPrecip Output incremental precip from cumulative precip, handles reset.
decodes.tsdb.algo.PythonAlgorithm OpenDCS 6.2 Python Algorithm
decodes.tsdb.algo.RdbRating Single independent variable rating using USGS RDB files
decodes.tsdb.algo.Resample Resamples an input to an output with a different interval using interpolation or fill
decodes.tsdb.algo.ReservoirFull Given capacity and storage, output % full and storage remaining
decodes.tsdb.algo.RunningAverageAlgorithm Output a running average of a single input over specified period.
decodes.tsdb.algo.ScalerAdder output = in1*coeff1 + in2*coeff2 ... in10*coeff10
decodes.tsdb.algo.Stat Given a single input output statistics for specified period: average, min, max, median, std dev
decodes.tsdb.algo.SubSample Subsample a short-interval input to a longer interval output by skipping unneeded values
decodes.tsdb.algo.SumOverTimeAlgorithm Sum a single input param over time
decodes.tsdb.algo.TabRating Rating of a single independent param using a 2-column ASCII file.
decodes.tsdb.algo.UsgsEquation output = A * (B + input)^^C + D
decodes.tsdb.algo.VirtualGage Given input upstream and downstream gages, use interpolation to estimate an intermediate stage.
```

**Comment by MikeNeilson** [comment]
What do y'all think about, instead of using that file above, we just scan $DCSTOOL_HOME and $DCSTOOL_USERDIR for XML files containing algorithm definitions and render those results to the user?

1. We can limit the results to those which haven't been imported
2. We'd also have the rest of the definition of the algorithm to populate for the user
3. Would also dovetail into the "initial database setup" we need to setup.
