### ISSUE TITLE
opendcs.jar pushed to maven central

### ISSUE THREAD

**Issue by MikeNeilson** [opendcs/opendcs#56]
**Is your feature request related to a problem? Please describe.**
Puah the opendcs.jar to mavencentral so those making alogritjms or projects (like the rest api) can have a well defined target for build tools.

**Describe the solution you'd like**
I'll start with pushing snapshots to the github package repo.

**Describe alternatives you've considered**
Maven is the standard distribution point.

**Additional context**
Wtih the various projects in different repos and local custom dev this will make things a bit easier.

Though we will have some issues with keysigning as thay is a requirement for maven central upload.

**Comment by adamkorynta** [comment]
I think it would also be worth publishing an SBOM at the same time. This GitHub Action uses Syft and can create either CycloneDX or SPDX formats. https://github.com/anchore/sbom-action

**Comment by MikeNeilson** [comment]
That doesn't sound unreasonable. Thought I think I'll do that in stages. just the jar up to maven central is confusing enough with getting the keys and such setup.

**Comment by adamkorynta** [comment]
yeah seems worth a separate ticket if this was something we wanted

**Comment by MikeNeilson** [comment]
The jar, with javadoc and sources are now pushed to maven central.
