### ISSUE TITLE
Custom Python Algorithms Don't Work in 7.0.12 PC Client (that worked in 6.8.14), without copying 3 files from python dirrectory

### ISSUE THREAD

**Issue by zamusacelre** [opendcs/opendcs#560]
**Describe the bug**
User upgraded from 6.8.14 to 7.0.12 on both server and client side.  After upgrading on the server, computations are running smoothly.  However, some custom python algorithms are not running/completed successfully when called form the computation editor from the PC client.  To address the issue, the user copied 3 files form the Windows PC client folder "python" (cp-funcs, PyAlgoEnv, and python-builtin) to the 7.0.12 opendcs 'python' folder.  After moving these three files the computation could be exectued.

**To Reproduce**
1. Be able to run a computation that uses a custom python algorithm from Windows PC client 6.8.14 
2. Upgrade on server and windows PC client to 7.0.12
3. Launch computation editor and test computation for a custom algorithm
4. Computation does not run.

**Expected behavior**
Computation should run.

**Screenshots**
Work around was moving the three files identified above.  Will this step be required of every office upgrading from 6.8.14?  Is there another work or code-side  modificaiton? Otherwise we may need to provide some guidance to offices for when they upgrade.

**Desktop/ServerSide (please complete the following information):**

**Comment by MikeNeilson** [comment]
See #519, There's a simple manual fix, but we're going to get a proper fix in for the next release.

**Comment by zamusacelre** [comment]
Thanks Mike - what is the simple manual fix? This might be something we may want to include some notes on the release page if it will likely impact multiple offices.   I am not sure in the content listed above if that is those three files were unique to the office at hand, or universal?

**Comment by MikeNeilson** [comment]
No that error message means your database is a bit too far behind and we'll need to update it. The updates are *too* 6.8 so will still work with 6.8.14 and 7.0.12
