### ISSUE TITLE
Initial Setup of an XML database

### ISSUE THREAD

**Issue by MikeNeilson** [opendcs/opendcs#576]
In reference to initial setup:

              I agree with your point about this PR already getting somewhat large.

Though not with during the installer, I think.

You've suggested just a zip, so then when would it happen?
That would be additional work to add to the installer, though it wouldn't be super difficult, basically just the same logic we currently have in the decj files + dbimport.

_Originally posted by @MikeNeilson in https://github.com/opendcs/opendcs/issues/569#issuecomment-2124786880_

I do want to create a GUI to manage the Schema and Baseline imports, while there is no "SQL Schema" in the XML hooking that into the general system would allow for consistent meta data imports.

But that's going to take time so I'm trying to figure out the "best now" solution for someone starting from nothing and just getting some simple decoding happening.

**Comment by ktarbet** [comment]
I think this issue is solved with the change recently made to decj.bat , assuming the zip file has a starter edit-db.?

```bat
  xcopy %APP_PATH%\edit-db %DCSTOOL_USERDIR%\edit-db /E /I

```

**Comment by MikeNeilson** [comment]
Yep, I think that is sufficient for now.
