### ISSUE TITLE
izpack installer doesn't work in console

### ISSUE THREAD

**Issue by MikeNeilson** [opendcs/opendcs#58]
**Describe the bug**
Expected 6.8.14 installer to work in console. 

**To Reproduce**
java -jar opendcs-ot-6.8.14.jar

**Expected behavior**
Terminal prompts for install

**ServerSide (please complete the following information):**
 - OS: [Ubuntu/Raspberry Pi]
 - Version [6.8.14]

**Additional context**
Whatever I did to the 7.1.0 installer file let's this work. maybe it's a different version as I don't believe I changed any settings.

**Comment by agilmore2** [comment]
Install works for me on Fedora 34. Haven't tested the result though. Did you provide the command line '-console' argument?


`[agilmore@agilmorel2 opendcs]$ java -jar ~/Downloads/opendcs-ot-6.8.14.jar -console
Welcome to the installation of OPENDCS Open Data Collection System 6.8.09!
 - Cove Software, LLC <info@covesw.com>
 - U.S. Army Corps of Engineers <Webmaster-HEC@usace.army.mil>
 - U.S. Bureau of Reclamation <hdbsupport@precisionwre.com>
The homepage is at: http://www.covesw.com
press 1 to continue, 2 to quit, 3 to redisplay
1
Select target path [/home/agilmore/workspace/opendcs] 
/tmp/opendcs
press 1 to continue, 2 to quit, 3 to redisplay
1
[ Starting to unpack ]
[ Processing package: OpenDCS Base (1/6) ]
[ Processing package: XML Database Template (2/6) ]
[ Processing package: Docs (3/6) ]
[ Processing package: TSDB Computation Components (4/6) ]
[ Processing package: Open Time Series Database Schema and Components (5/6) ]
[ Processing package: LRGS (6/6) ]
[ Unpacking finished ]
[ Console installation done ]
`

**Comment by MikeNeilson** [comment]
Hmm. Not yet. Still makes me wonder what the difference is though.

**Comment by MikeNeilson** [comment]
Yep. that works. thanks for reminding me about the command line switches.

**Comment by agilmore2** [comment]
There's also the automated install method using '-options <filename>' where
the file contains INSTALL_PATH=<directory>

I don't have the Puppet module I use for this published as open source yet.
:/
