### ISSUE TITLE
Add reverse rate algorithm for CCP

### ISSUE THREAD

**Issue by adamkorynta** [opendcs/opendcs#598]
**Is your feature request related to a problem? Please describe.**
NWP is trying to move cron jobs to CCP algorithms

**Describe the solution you'd like**
Add a reverse rate algorithm to use.

**Describe alternatives you've considered**
SPK has achieved this through custom scripts. Would like this to be something more broadly supported.

**Additional context**
Need to verify that necessary ratings are monotonically increasing. Otherwise reverse rate would need to be customized to remove duplicates and accuracy is diminished.

**Comment by MikeNeilson** [comment]
work will be done as part 0f #503. May also see if I can do the same for the built in Ratings (Tab and Rdb).
