### ISSUE TITLE
Initial Build issues

### ISSUE THREAD

**Issue by agilmore2** [opendcs/opendcs#6]
Git clone followed by ./gradlew build results in the following error:
`         Could not get resource 'https://mvnrepository.com/artifact/postgresql/postgresql/42.2.14/postgresql-42.2.14.pom'.
`
Updating the group name to org.postgresql fixes that, but then the compile fails with many missing libraries:
```
/home/agilmore/workspace/opendcs/build/src/decodes/cwms/rating/CwmsRatingSingleIndep.java:100: error: package hec.lang does not exist
import hec.lang.Const;
               ^
/home/agilmore/workspace/opendcs/build/src/decodes/cwms/rating/CwmsRatingSingleIndep.java:123: error: cannot find symbol
        RatingSet ratingSet = null;
        ^
  symbol:   class RatingSet
  location: class CwmsRatingSingleIndep
/home/agilmore/workspace/opendcs/build/src/decodes/cwms/CwmsSiteDAO.java:85: error: package usace.cwms.db.dao.ifc.loc does not exist
import usace.cwms.db.dao.ifc.loc.CwmsDbLoc;
```

What steps are required to get the project to build?

**Comment by agilmore2** [comment]
Linked build.xml and dep/ to a ant build directory, and after manually downloading poi-5.0.0.jar, was able to build with ant.

**Comment by MikeNeilson** [comment]
There are still a few kinks to work out in the build process. A better example of where we're trying to get to is the https://github.com/opendcs/opendcs/tree/build/setup_ant_with_deps branch. 

I removed gradle from the project , but it's still the maven style dependencies. I've had it reported to me that it still has some issues but haven't had time to dig further. My intent is to get back at it with Mike M in the next month or so.

But the work-around you figured out is reasonable for now.
