### ISSUE TITLE
Algorithm to calculate relatively humidity.

### ISSUE THREAD

**Issue by MikeNeilson** [opendcs/opendcs#606]
**Is your feature request related to a problem? Please describe.**

Given a temperature and a dew point calculate relative humidity.

**Describe the solution you'd like**
A simple algorithm

**Additional context**

`
To calculate relative humidity with temperature and dew point, follow the given instructions:
1.	Measure the air temperature T, in °C.
2.	Find out the dew point temperature Dp, in °C.
3.	Calculate relative humidity RH using the formula, `RH = 100 × {exp[17.625 × Dp/(243.04 + Dp)]/exp[17.625 × T/(243.04 + T)]}`.

**Comment by heysuhas** [comment]
## Algorithm Steps

1. ### Input Validation:

-  Ensure the input temperatures are numeric.
-  Check that the dew point (D<sub>p</sub>) is not greater than the air temperature (T), as it’s physically impossible for the dew point to exceed the air temperature.

2. ### Calculate the Relative Humidity (R<sub>H</sub>):
-  Use the formula provided to compute the relative humidity.

## Python Implementation

```py
import math

def calculate_relative_humidity(T, Dp):
    # Validate input types
    if not isinstance(T, (int, float)) or not isinstance(Dp, (int, float)):
        raise ValueError("Temperature and Dew Point must be numeric values.")
    
    # Validate dew point not greater than temperature
    if Dp > T:
        raise ValueError("Dew Point cannot be greater than Air Temperature.")
    
    # Calculate the numerator
    numerator = math.exp((17.625 * Dp) / (243.04 + Dp))
    
    # Calculate the denominator
    denominator = math.exp((17.625 * T) / (243.04 + T))
    
    # Calculate the relative humidity
    RH = 100 * (numerator / denominator)
    
    return RH

# Example usage
try:
    T = 25  # Air temperature in °C
    Dp = 15  # Dew point temperature in °C

    RH = calculate_relative_humidity(T, Dp)
    print(f"Relative Humidity: {RH:.2f}%")
except ValueError as e:
    print(e)
```

**Comment by MikeNeilson** [comment]
Thanks! That doesn't directly apply to our algorithm system (it's primarily specific Java code) but the logic you've provided will be helpful to whomever does the implementation.

I will try improve the documentation for our algorithm system this week. We have a few new people starting to create some and it would be good to create some general guidance.

**Comment by oskarhurst** [comment]
Hi @heysuhas, by any chance can you provide more information about how Temperature and Dew Point Data are retrieved and what forms they are in.  To be more specific, whether both pieces of data are stored as time series with Identical intervals. For example is Temperature hourly and dew point bidaily, in which case we may was to interpolate that best dew point to match the time slice of the temperature, or can we assume that point pieces of data must have there corresponding counter part at each specific time.
