### ISSUE TITLE
HDB Computation Processor Cache Broken

### ISSUE THREAD

**Issue by agilmore2** [opendcs/opendcs#611]
**Describe the bug**
Looks like the differences in how HDB handles the site table has been completely removed from the computation cache fill code path? The buildSiteQuery function override used to handle the differences, and that was removed. This has completely broken HDB computation processor usage.

```
DBG1    06/14/24 15:39:01 259 cp_comp_ts_parm recs read.
DBG3    06/14/24 15:39:01 HDB Query1 'select SITE_DATATYPE_ID, SITE_ID, DATATYPE_ID from HDB_SITE_DATATYPE'
DBG3    06/14/24 15:39:01 HDB Query1 'select SITE_ID, DATATYPE_ID from HDB_SITE_DATATYPE where SITE_DATATYPE_ID = 32169'
FAILURE 06/14/24 15:39:01 HdbSiteDAO Error in readSite(a.site_id=5040): java.sql.SQLSyntaxErrorException: ORA-00942: table or view does not exist

WARNING 06/14/24 15:39:01 Exception filling computation hash.
WARNING 06/14/24 15:39:01 decodes.tsdb.DbIoException: Error in readSite(a.site_id=5040): java.sql.SQLSyntaxErrorException: ORA-00942: table or view does not exist

        at opendcs.dao.SiteDAO.readSite(SiteDAO.java:402)
        at opendcs.dao.SiteDAO.getSiteById(SiteDAO.java:149)
        at decodes.tsdb.TimeSeriesDb.getSiteById(TimeSeriesDb.java:1448)
        at decodes.hdb.HdbTimeSeriesDb.expandSDI(HdbTimeSeriesDb.java:380)
        at opendcs.dao.ComputationDAO.fillCache(ComputationDAO.java:245)
        at opendcs.dao.ComputationDAO.listCompsForGUI(ComputationDAO.java:564)
        at decodes.tsdb.ComputationApp.checkMissingChecks(ComputationApp.java:1155)
        at decodes.tsdb.ComputationApp.runAppInit(ComputationApp.java:622)
        at decodes.tsdb.ComputationApp.runApp(ComputationApp.java:322)
        at decodes.tsdb.TsdbAppTemplate.execute(TsdbAppTemplate.java:180)
        at decodes.tsdb.ComputationApp.main(ComputationApp.java:668)
```

**Additional context**
https://github.com/opendcs/opendcs/blob/master/src/main/java/opendcs/dao/SiteDAO.java#L387 doesn't work on HDB. 

I'm worried how many other subtle breakages have occurred in these refactors.

**Comment by MikeNeilson** [comment]
Probably a few, this Dao in particular was rather... not subtle. 

Though I am surprised, the logic was pushed completely to the Hdb implementations so it shouldn't even be calling SiteDAO. The behavior for HDB shouldn't have changed.

Though it's also entirely plausible I misunderstood something when I moved it, but looking at the query error, isn't it trying to read from the correct table but it either isn't there or doesn't have access?

**Comment by MikeNeilson** [comment]
gah, nope, I totally missed that sorry. I've been trying to move code that was that different to the invididual database implementations (SiteDAO shouldn't need to know about different tables) and while the larger query was clear I missed this case.

I can ahead and dig it up and do it but the proper (err, preferred?) solution is to override readSite in the HdbSiteDao class.

**Comment by agilmore2** [comment]
Thanks, I'm working on the override now

**Comment by MikeNeilson** [comment]
Sounds good. SiteDAO is the one that had the most impossible to manage differences, so it's the only one I ripped up this much. The other DAO had more simple difference that I still want to shift around but felt they could wait.
