### ISSUE TITLE
dbimport does not ignore historical versions

### ISSUE THREAD

**Issue by adamscarberry** [opendcs/opendcs#64]
**Describe the bug**
When using dbimport, the docs and command line help indicates that historical versions will be excluded by default.  This doesn't appear to be the case.

**To Reproduce**
1. run dbimport against a platform export file with historical version included
2. check database or opendcs GUI
3. historical versions will appears

**Expected behavior**
Historical versions should not be imported by default.

**Screenshots**
![image](https://user-images.githubusercontent.com/46494851/179785151-453db24f-b8ec-4f40-b772-1023c3d6f925.png)

**Desktop/ServerSide (please complete the following information):**
 - OS: Linux Docker container
 - DECODES DB: OpenTSBD/Postgresql
 - openjdk version "11.0.15" 2022-04-19
 - OpenJDK Runtime Environment (build 11.0.15+10-post-Debian-1deb11u1)
 - OpenJDK 64-Bit Server VM (build 11.0.15+10-post-Debian-1deb11u1, mixed mode, sharing)

**Additional context**
`allowHistoricalArg` referenced below doesn't appear to be used in code:
 https://github.com/opendcs/opendcs/blob/b8d31a04b72395fbf8c5aa08e0d90a9be392849a/src/main/java/decodes/dbimport/DbImport.java#L153

zipped platform export below:
[p.lrn.xml.zip](https://github.com/opendcs/opendcs/files/9142434/p.lrn.xml.zip)

**Comment by mikecovesw** [comment]
Fix completed 8/1/2022

**Comment by adamscarberry** [comment]
awesome.  thanks @mikecovesw !

**Comment by MikeNeilson** [comment]
will be in next release.
