### ISSUE TITLE
Time Series Group Editor - updates to Column and Windows to Select and Filter Suggestions

### ISSUE THREAD

**Issue by zamusacelre** [opendcs/opendcs#68]
**In the Time Series Groups Defined in the Database - add column for Number of Time Series and or # of comps**
There is a column for Group ID, Name, Type, Description. It would be a nice/helpful addition if there was another column that said how many time series were in that group. And it would be helpful if there was a column that showed how many computations that list is used in (it doesn't ncesarily have to show which comp that is - just if it is selected at all -- kind of like how the Configs tab in the DECODES Database Editor.

**Selecting Time Series**
There are two minor thing that would be nice:
1. When you are editing a group and there are three sections to the tab ("Time Series Group Members", "Sub-Group Members", and "Select by site, data-type, interval, or statistics-code", it would be nice if those sections could be expanded/reduced (so less scrolling when there are lot of pathnames selected).
2. When you click "add" on the right side of "Time Series Group Members", the Time Series List shows ALL the pathnames in the database. It would super helpful if there was drop down menu or something to filter things out easier - for example as simple as like in the CWMSVue - where you can select by Location, Param, or ParamType, and Interval, Duration and version.  

These are just minor suggestions that I think will really improve the overall ease of using the tool, so that it is less of a headache to scroll through every single pathname in your database.

Thank you!

**Comment by mikecovesw** [comment]
In the group list panel, adding a column for "# comps" would be an easy addition. The column for "# TimeSeries" would involve "evaluating" each group, which may slow the display of the panel. Also, it's dynamic: A new previously unseen Stage value may become a member of groups when the time series is created.

For improvement #1: I see two possibilities. We could use a JSplitPane to allow the user to adjust the size of each pane as needed. This is done in the "Edit Decoding Script" Dialog:

![Screen Shot 2022-08-06 at 11 59 39 AM](https://user-images.githubusercontent.com/6698270/183256761-e70b4128-0423-41a5-9bd0-58a136eabc48.png)

Alternately, there could be a button to show or hide each of the 3 sections "time Series Group Members", "sub-group members" and "select by site..."

For #2: currently you can sort the list by clicking column headers. E.g. click the "Location" column header sorts the list by Location and then by the residual columns (Param, ParamType, etc.)

**Comment by MikeNeilson** [comment]
For the counts i may be useful to put those queries in a background thread and update on an interval only when the data is available. The dynamic nature of those counts is true for everything at this point. Another app admin could be in the database and create a new computation.

@adamkorynta may have some good insight into how to handle that. My first thought is using RxJava but that may necessitate the move to Java 1.8... which we should probably do anyways given java 1.7 hasn't been supported in I don't know how long.

**Comment by adamkorynta** [comment]
A scheduled executor service with a single thread count would be sufficient in Java 1.7, we'd just need to display "--" or something to indicate that the count is still loading when brought up initially.

For a move to RxJava, it would probably be useful to create an epic and track down the number of places we would want to dynamically load/refresh data.

**Comment by mikecovesw** [comment]
I don't have a problem an update to the ant build that will require Java 8.

ScheduledExecutorService looks like an interesting approach. Care will be needed in accessing the DAO methods from multiple threads.

Adam -- do you want to work on this, or shall I assign it to myself?

**Comment by adamkorynta** [comment]
I can pick this one up.

**Comment by adamkorynta** [comment]
There is already a manual refresh button in that GUI, do we really need to poll at an interval?

**Comment by MikeNeilson** [comment]
Oh, probably not then. I can see the value in it but maybe easier to just start with the refresh button.
