### ISSUE TITLE
DECODES Platforms tab - Filtering does not stay when trying to sort by column

### ISSUE THREAD

**Issue by jbatterman** [opendcs/opendcs#682]
**Describe the bug**
When applying a filter in the Platorms tab of the DECODES Database Editor, the initial table list looks filtered correctly.  However, if you subsequently try to sort by a column (i.e., clicking on Transport-ID to sort alphabetically), the filtering goes away.

**To Reproduce**
1. Go to DECODES Database Editor Platform tab
2. Apply Agency Filter of "CO DWR" (for NWDM database)
3. Click on "Transport-ID" column to sort by that column
4. Full list of stations applies to the sort

**Expected behavior**
Only the filtered table should be available on the column sort.

**Screenshots**
Upon first opening of Platform tab:
![image](https://github.com/user-attachments/assets/97c7472d-066c-4c6d-b206-0ab37f0f488f)

Applying filter (see larger scroll bar indicating reduced table):
![image](https://github.com/user-attachments/assets/13f6b6bd-e9a8-476d-8e02-cb72fe1cd115)

After clicking the "Transport-ID" column to sort:
![image](https://github.com/user-attachments/assets/91d1e6bb-3eba-4bdf-9af0-8b8b22076919)

**Desktop/ServerSide (please complete the following information):**
 - OS: Windows 10, using OpenDCS 7.0.13 RC05
 - Version (server) 7.0.13 RC05

**Comment by MikeNeilson** [comment]
This will likely involve some more drastic work to start using the built-in sorting. Unless someone creates a PR rather quickly this won't get fixed in 7.0.13.
