### ISSUE TITLE
DECODES Database Editor Table Sorting

### ISSUE THREAD

**Issue by jbatterman** [opendcs/opendcs#683]
**Describe the bug**
I have not fully tested all tables, but noticed that the sorting seems to be broken again in this release.  On the Routing Tab, I sorted by "Name" to alphabetize the routing specs and start editing some properties.  The table sorting looked like it worked, but when I try opening a row it is opening the wrong row.

**To Reproduce**
1. Open DECODES Database Editor Routing Tab
2. Click on "Name" to sort by that column
3. Click on "CODWR-WebService-Flow1_CWMS" and choose Open (in NWDM database)
4. The "Metar_Testing" routing spec is opened

**Expected behavior**
The table sorting should follow through so opening rows to edit should match what is shown on the table.

**Screenshots**
Sorted Routing tab by Name:
![image](https://github.com/user-attachments/assets/7f30b827-0d16-4b53-8234-0d26546aeac4)

Opening CODWR-WebService-Flow1_CWMS:
![image](https://github.com/user-attachments/assets/f95ca7ce-dd51-43bb-a43a-f5ef00326097)

**Desktop/ServerSide (please complete the following information):**
 - OS: Windows 10 OpenDCS 7.0.13-RC05
 - Version (server) 7.0.13-RC05

**Additional context**

**Comment by MikeNeilson** [comment]
Thanks. I thought I was going insane a few days ago seeing the same problem.

**Comment by MikeNeilson** [comment]
Additional note, after delete, either the wrong row was used (quite likely) or there's also an issue with the table re-rendering correctly.

**Comment by MikeNeilson** [comment]
Yep, it's the way the TableModels interact. It seems to behave okay if you don't sort again (reverse) on the same column. I'll start updating the models to use the correct methods. Should be able to add some better behavior display wise as well.
