### ISSUE TITLE
Screening Editor - 2 bugs - renaming and screening ID and TS assignment turn Active to False

### ISSUE THREAD

**Issue by zamusacelre** [opendcs/opendcs#69]
**1. Renaming Screening ID**
There is a an option to rename the screening ID - which would be helpful, especially as we add new screening IDs and are getting things set up (as opposed to having to recreate them over and over).  However this feature doesn't save.

On a separate note - it would be nice if the screenid ID name could be longer, I think there is a limit right now.

**TS Assignment Active status**
On the TS Assignment tab under the Screening Editor, the option to turn active status to inactive does not work. If you click "set/Clear Active" and try to reassign to Inactive the status does not change.  On a separate note - not sure if this is possible ,but if you could select a hanful at one and change the status - that would be very helpful (if that functionality doesn't already exist).

Thanks!

**Comment by mikecovesw** [comment]
For issue #1, the limit of 16 chars is set in the CWMS schema and I cannot change it. I did add code to check to make sure the new screening ID is neither blank or over the 16-char limit.
The TS active status bug is fixed.
BTW, you can select multiple  TS assignments and activate/deactivate them all in one operation.

**Comment by MikeNeilson** [comment]
I'm checking with the CWMS DB team. we can probably increase that. I think 16 characters just tends to be our default for some reason.
