### ISSUE TITLE
13-RC7  Rating read error

### ISSUE THREAD

**Issue by vwreck86** [opendcs/opendcs#717]
I switched from 12-rc3 to 13-rc7 and immediately began seeing "Cannot read rating warnings" for every timeseries going through a computation utilizing "CwmsRatingSingleIndep" algorithm.   I reverted back after seeing this warning for 450+ ratings of various types within about an hour.    

Example from comp log: 

"WARNING 10/02/24 15:13:35 compproc Computation 'UsbrLakeStor' DbCompException: decodes.tsdb.DbCompException: Cannot read rating for 'Turquoise.Elev;Stor.Linear.Step;USBR': hec.data.RatingException: java.lang.StringIndexOutOfBoundsException: String index out of range: -1"

**Comment by MikeNeilson** [comment]
... whelp. Is there more log than that?

If not, can you run that manually (with the RC07 compedit, and from a terminal/cmd to make sure we capture standard output. Possible the rest of that error is getting hidden and the full stack trace would help a lot.

**Comment by MikeNeilson** [comment]
Thanks for the log, sadly that didn't have anything extra. I did just find a possibly related issue so I'll try connecting with the latest change and running the computation manually on your system (I won't save anything.)

**Comment by vwreck86** [comment]
Not a problem. I did revert back to 12-rc3 because our data wasn’t making it through the computations.

From: Mike Neilson ***@***.***>
Sent: Friday, October 4, 2024 8:11 AM
To: opendcs/opendcs ***@***.***>
Cc: Ritchie, Kevin S CIV USARMY CESPA (USA) ***@***.***>; Author ***@***.***>
Subject: [Non-DoD Source] Re: [opendcs/opendcs] 13-RC7 Rating read error (Issue #717)


Thanks for the log, sadly that didn't have anything extra. I did just find a possibly related issue so I'll try connecting with the latest change and running the computation manually on your system (I won't save anything.)
