### ISSUE TITLE
Add full OpenDCS Build/Version into Title bar of Toolkit & into Help menu

### ISSUE THREAD

**Issue by jbatterman** [opendcs/opendcs#732]
**Is your feature request related to a problem? Please describe.**
It's difficult to tell what version of OpenDCS I'm running (particularly the RC) from the toolkit or the Help menu.  In OpenDCS 7.0.13, the release is listed as "OPENDCS 7.0" in the title bar and the build is only listed as 7.0.13 in the Help menu, no RC.  In OpenDCS 7.0.1, the full version is listed in the title bar.

**Describe the solution you'd like**
Request the full build name appear on the title bar of the toolkit or in the Help menu.

**Additional context**
Version 7.0.1:
![image](https://github.com/user-attachments/assets/b3cd7b61-c973-49e4-ab92-613f9854a4a7)

![image](https://github.com/user-attachments/assets/fbf913f3-3aed-4303-be6d-0acc847f47da)

Version 7.0.13, all RC's tested so far:
![image](https://github.com/user-attachments/assets/ab194a82-cae0-457c-bb88-e7db5b82e705)

![image](https://github.com/user-attachments/assets/d5fdcc93-17e2-447b-a484-6eff2b735b8b)

**Comment by MikeNeilson** [comment]
The was intentionally hard coded due to issues with the build and repeatability, we'll "fix" it once we've officially moved to the new build system so expect this to work for releases *after* 7.0.13.

**Comment by jbatterman** [comment]
Sounds good, thank you!
