### ISSUE TITLE
DECODES Platforms: Filtering by Agency, Config, Transport-ID isn't working

### ISSUE THREAD

**Issue by jbatterman** [opendcs/opendcs#734]
**Describe the bug**
In the DECODES Platforms tab, I am able to filter by Platform and by Agency=CWMS but nothing else (in my spot checking).  Choosing any other filters produces an empty table.

**To Reproduce**
1. Open DECODES Database Editor for HEC Test Database - NWK Office ID
2. Activate Platforms tab
3. Select a filter for Transport-ID, Agency, or Config
4. See empty table below

**Expected behavior**
Expected table to show results of chosen filter.

**Screenshots**
Before Filter:
![image](https://github.com/user-attachments/assets/3c60ab9f-abc2-4b65-a190-fa42c09d3006)

Choosing Agency Filter (not CWMS):
![image](https://github.com/user-attachments/assets/d86a3e79-73c5-4b12-80b2-3428b3519065)

Choosing Platform Filter:
![image](https://github.com/user-attachments/assets/b8314522-648f-44e1-9802-24260b3790de)

**Desktop/ServerSide (please complete the following information):**
 - OS: Windows 10, OpenDCS 7.0.13-RC08
 - Server Version OpenDCS 7.0.13-RC07

**Comment by MikeNeilson** [comment]
well, it's definitely something with the NWK datatset works just fine in my local test database.

**Comment by MikeNeilson** [comment]
No, it's our profile. We add the "show designator" option which changed an offset that should've been looked up.

**Comment by jbatterman** [comment]
This works with the newest release candidate.  Thanks!
