### ISSUE TITLE
Space in install directory causes issues

### ISSUE THREAD

**Issue by MikeNeilson** [opendcs/opendcs#79]
**Describe the bug**
At least on windows if spaces are put in the installation path name the programs won't start and the message isn't super clear

**To Reproduce**
1. download opendcs-ot-<version>.jar and run it
2. set an installation path with a space in it
3. finish install, attempt run launcher_start.bat
4. See error (only if run from command line)

**Expected behavior**
We either shouldn't allow spaces and warn the user during install or the batch and shell files should be robust enough to handle it.

**Desktop**
 - OS: Windows
 - Version 6.8.14 and future and previous versions

**Additional context**
User was setting up new version and wasn't getting any error message but even launcher_start failed to open.

**Comment by mikecovesw** [comment]
I agree. This is in the "I never got around to it" category. To allow spaces would (I think -- I'm not a microsoft batch script expert) adding quotes around the places where INSTALL_PATH is referenced. Example in dbedit.bat:
    @$INSTALL_PATH\bin\decj decodes.dbeditor.DecodesDbEditor %*%
The first string would have to be quoted. something along the lines of:
   "@$INSTALL_PATH\bin\decj" decodes.dbeditor.DecodesDbEditor %*%
Again -- I'm not sure that this is the right syntax.

This would have to be done for all the .bat scripts under install/bin.

Do we need to worry about spaces in directories under Unix/Linux? Who in their right mind would do such a thing?

**Comment by MikeNeilson** [comment]
Even with Unix you'd be surprised. But yeah I think it's just quotes in batch and bash.

**Comment by ktarbet** [comment]
I plan to update the windows batch files so they don't need hardcoded paths based on $INSTALL_PATH.  

Goal: The install should be able to be copied around and handle spaces in directory names.

**Comment by ktarbet** [comment]
I found postinstall.bat that deletes some jars that may not even exist.    Can postinstall.bat be retired/cleaned?

Note:   There is a izpack/post-process.xml   That references postInstallClean.bat and postInstallClean.sh -- but I don't think those files exist.

**Comment by MikeNeilson** [comment]
Probably, they were likely either there by default or for a plan idea that never materialized.
