### ISSUE TITLE
OpenDCS 7.0.13-RC08 Server Side Log Size 

### ISSUE THREAD

**Issue by vwreck86** [opendcs/opendcs#794]
We are running OpenDCS 7.0.13-RC08 on our T7 server.  Our comp,logs and routsched.logs are no longer rolling over at a certain size;  one of our comp.logs was 43 Gb before we manually rolled it.

**Comment by MikeNeilson** [comment]
for anyone that works on this. We (well I) accidentally remove the "how much has been written" check in the filelogger.
