### ISSUE TITLE
Decode Numbers with Comma Separators

### ISSUE THREAD

**Issue by tsressin** [opendcs/opendcs#829]
**Is your feature request related to a problem? Please describe.**
Yes, I am unable to decode numbers that use a comma separator, for example 1,234.  I can decode it as a string, but that causes the cwms consumer to fail.

If there already is a way to do this, please let me know how.

**Describe the solution you'd like**
I would like decodes decoding language to recognize this type of number as a number.  

**Describe alternatives you've considered**
I have no alternatives available in OpenDCS (as far as I know).  I have my own script that will do this outside OpenDCS that I would like to get away from.

**Additional context**
![image](https://github.com/user-attachments/assets/dd9be0c2-8f52-45f0-b7e9-e2c264339f1f)

**Comment by ktarbet** [comment]
You could try the regex method. 

https://opendcs-env.readthedocs.io/en/stable/start-decoding.html#regex-function-regex-expression

this was created in June.

https://github.com/opendcs/opendcs/issues/338
